### ISSUE TITLE
file lacks file extension

### ISSUE THREAD

**Issue by oawd** [saulpw/unzip-http#17]
After the installation, the file "unzip-http" was lacking the extension ".py". Because of this, the tool could not be used. After correcting this, the tool could be used.

I also have a question about the syntax that is separate from this issue . How are multiple filenames separated?

**Comment by saulpw** [comment]
@oawd what platform are you working on?  The script works well for me on Linux, and I believe it works on OSX too.  Is the executable bit set?

Also, what do you mean about "multiple filenames"?  I think you just have to separate them with spaces?

**Comment by saulpw** [comment]
Ah, yes, the standard CLI separator character.  Glad you got it working!

**Comment by anjakefala** [comment]
If you install the latest release with `pip3 install unzip-http`, there should now be support for `unzip_http.py` as an executable!
